DISCORD_TOKEN = 'PLACE YOUR DISCORD TOKEN HERE'

MESSAGES_TOML = '''
[commands]

about = """
This is a Rust-based Discord bot created by UmmIt, designed to help students manage their assignments and coursework. It provides timely reminders and notifications for upcoming deadlines, ensuring you never miss an important task.

**Check it out on GitHub: [GitHub Repository](https://github.com/UmmItC/rs-college-deadline).**
"""
'''
